config/routes.rb
Rails.application.routes.draw do
  root to: 'static#index'
  resources :football_players, except: [:new, :edit]

end

app/models/football_player.rb
class FootballPlayer < ActiveRecord::Base
	validates :name, presence: true
	validates :handSizeInches, presence: true

	validates :name, length: { minimum: 2 }
	validates :name, length: { maximum: 200 }
	validates :name, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/football_players_controller.rb
class FootballPlayersController < ApplicationController
  before_action :set_football_player, only: [:show, :update, :destroy]

  def index
    render json: FootballPlayer.all
  end

  def show
    render json: @football_player
  end

  def create
    football_player = FootballPlayer.new(football_player_params)

    if football_player.save
      render json: football_player 
    else
      render json: football_player.errors, status: :unprocessable_entity #uses 422 for the status code - http://guides.rubyonrails.org/layouts_and_rendering.html
    end
  end

  def update
    if @football_player.update(football_player_params)
      render json: @football_player
    else
      render json: @football_player.errors, status: :unprocessable_entity
    end
  end

  def destroy
    @football_player.destroy
    render json: @football_player
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_football_player
      @football_player = FootballPlayer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def football_player_params
      params.require(:football_player).permit(:name, :handSizeInches)
    end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController

  def index
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/football_players/_form.html.erb
<%= form_for(@football_player) do |f| %>
  <% if @football_player.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@football_player.errors.count, "error") %> prohibited this football_player from being saved:</h2>

      <ul>
      <% @football_player.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :handSizeInches %><br>
    <%= f.number_field :handSizeInches %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/football_players/new.html.erb
<h1>New football_player</h1>

<%= render 'form' %>

<%= link_to 'Back', football_players_path %>

app/views/football_players/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @football_player.name %>
</p>

<p>
  <strong>Handsizeinches:</strong>
  <%= @football_player.handSizeInches %>
</p>

<%= link_to 'Edit', edit_football_player_path(@football_player) %> |
<%= link_to 'Back', football_players_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsAjaxCrud</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>